config/routes.rb
Rails.application.routes.draw do
  root  'static_pages#index'

  get  '/users' => 'static_pages#public'
  get '/admin' => 'static_pages#admin'

  resources :users, only: [:new, :create] do
    collection do
      get 'activate'
      get 'recovery'
      post 'reset_password'
      post 'create_new_password'
    end
  end

  resources :album_sessions, only: [:new, :create, :destroy, :index]
  resource :session, only: [:new, :create, :destroy]

  namespace :api, defaults: { format: :json } do
    get 'users/:user_id', to: 'public_users#show', as: "public_user"
    get 'users/:user_id/albums', to: 'public_albums#index', as: 'public_albums'
    get 'users/:user_id/albums/:id', to: 'public_albums#show', as: "public_album"
    resources :owners, only: [:show, :update]
    resources :albums, except: [:new, :edit]
    resources :subalbums, only: [:create, :update, :destroy, :show]
    resources :photos, only: [:create, :update, :destroy]
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def admin
    redirect_to new_session_url unless logged_in?
  end

  def public
  end

  def index
    @users = User.order('created_at').limit(3)
    render :index
  end

end

app/views/static_pages/_bottom_info.html.erb
<div class="bottom-info">
  <div class="create-first">
    <div class="top">
      <div class="header">CREATE YOUR FIRST GALLERY NOW.</div>
      <div class="free"><span class="underline">Free</span> forever. Upgrade when you need to.</div>
      <div class="get-started-guest"><%= link_to 'Get Started', new_user_url, { method: "get", class: "guest-login-button"} %></div>
    </div>
  </div>
  <div class="info">
    <div class="information">
      Twinkieset is created by me, <a href="http://www.karenling.net/">Karen Ling</a>, and this is my final project for <a href="http://www.appacademy.io/">App Academy</a>. This project showcases my knowledge of <i>Ruby on Rails</i> and <i>Backbone</i> primarily. Twinkieset is intended to be inspired by <a href="http://pixieset.com">Pixieset</a>. All images and content belong to their respective owners.
      <div class="github-link">
        <a href="https://github.com/karenling/project-proposal">
          <i class="fa fa-github fa-5"></i>
        </a>
      </div>
    </div>

    <div class="copyright">Created by <a href="http://www.karenling.net/">Karen Ling</a>. Twinkieset is a clone of <a href="http://pixieset.com">Pixieset</a>.</div>
  </div>
</div>

app/views/static_pages/_design_examples.html.erb
<div class="container-fluid design-examples">
  <div class="designed-to-impress">Designed To Impress</div>
  <div class="design-tagline">Dedicated online photo gallery for each of your clients, with beautiful cover and layout right out of the box.</div>

  <div class="desktop-options group">
    <div class="selected beautiful-design">Beautiful Design</div>
    <div class="gallery-design">The Gallery</div>
    <div class="space-design">Your Space</div>
  </div>

  <div class="desktop">
    <img src="http://images.karenling.net/aa/desktop-image.png" class="computer">
    <img src="http://images.karenling.net/aa/desktop-beautiful.png" class="desktop-screen beautiful">
    <img src="http://images.karenling.net/aa/desktop-gallery.png" class="desktop-screen gallery">
    <img src="http://images.karenling.net/aa/desktop-your.png" class="desktop-screen your">
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function () {
    var topOfDesignExamples = $('.design-examples').offset().top;
    var topOfAlbumExamples =  $('.example-albums').offset().top;
    var topOfBottomInfo =  $('.bottom-info').offset().top;
    $(window).resize(function () {
      var windowHeight = $(window).height();
      var splashHeight = $('.splash').height();
      $('.design-examples, .example-albums, .bottom-info').height(splashHeight);

      $('.design-examples').css('top', splashHeight);
      $('.example-albums').css('top', splashHeight*2);
      $('.bottom-info').css('top', splashHeight*3);

      $('.create-first').height(splashHeight-244);

      $('.example-albums .header').height(splashHeight-350);
      if ($(window).width() < 825) {
        $('.screenshot').width('400px');
        $('.user-item').addClass('collapse');
      } else if ($(window).width() < 1043) {
        $('.user-item').removeClass('collapse');
        $('.screenshot').width('100%');
      } else {
        $('.screenshot').width('300px');
      }

      topOfDesignExamples = $('.design-examples').offset().top;
      topOfAlbumExamples =  $('.example-albums').offset().top;
      topOfBottomInfo =  $('.bottom-info').offset().top;

      $(".welcome-link").click(function() {
        $('html, body').animate({
          scrollTop: 0
        }, 2000);
      });

      $(".design-link").click(function() {
        $('html, body').animate({
          scrollTop: topOfDesignExamples - 25
        }, 2000);
      });

      $(".examples-link").click(function() {
        $('html, body').animate({
          scrollTop: topOfAlbumExamples
        }, 2000);
      });
    });
    $(window).resize();

    $(window).scroll(function () {

      var currentPos = $('body').scrollTop();
      if (currentPos < topOfDesignExamples - 100) {
        $('.splash-navbar').fadeOut('fast');
        $('.options li').removeClass('current');
        $('.welcome-link').addClass('current');
      } else if (currentPos < topOfAlbumExamples) {
        $('.splash-navbar').fadeIn();
        $('.options li').removeClass('current');
        $('.design-link').addClass('current');
      } else {
        $('.options li').removeClass('current');
        $('.examples-link').addClass('current');
      }
    });

    $(window).scroll();

    $('.beautiful').hide();

    $('.beautiful-design').on('mouseover', function () {
      $('.beautiful, .gallery, .your').hide();
      $('.beautiful').fadeIn();
      $('.desktop-options > div').removeClass('selected');
      $('.beautiful-design').addClass('selected');
    })

    $('.gallery-design').on('mouseover', function () {
      $('.beautiful, .gallery, .your').hide();
      $('.gallery').fadeIn();
      $('.desktop-options > div').removeClass('selected');
      $('.gallery-design').addClass('selected');
    });

    $('.space-design').on('mouseover', function () {
      $('.beautiful, .gallery, .your').hide();
      $('.your').fadeIn();
      $('.desktop-options > div').removeClass('selected');
      $('.space-design').addClass('selected');
    });
  });
</script>

app/views/static_pages/_example_album.html.erb
<div class="user-item">
  <a href="/users#<%= user.id %>" target="_new">
    <img src="<%= user.screenshot %>" width="300px" class="screenshot">
    <div class="user-name"><%= user.business_name %></div>
  </a>
</div>

app/views/static_pages/_example_albums.html.erb
<div class="container-fluid example-albums">
  <div class="header">
    <div class="content">
      <div class="see-in-action">See It In Action</div>
      <div class="see-in-action-tagline">Twinkieset is trusted by some of the most inspiring professional photographers.</div>
      <%= button_to "Get Started", new_user_url, {method: 'get', class: 'get-started'} %>
    </div>
  </div>
  <div class="users">
    <% @users.each do |user| %>
      <%= render 'example_album', user: user %>
    <% end %>
  </div>
</div>

app/views/static_pages/_guest_login.html.erb
<form action="<%= session_url %>" method="POST">
  <input type="hidden" name="user[email]" value="erich@erichmcvey.com">
  <input type="hidden" name="user[password]" value="password">
  <input type="submit" class="guest-login-button" value="Guest Login">
</form>

app/views/static_pages/_main.html.erb
<div class="container-fluid splash">
  <nav>
    <a href="/"><img src="http://images.karenling.net/aa/logo.png" height="16px" class="pull-left"></a>

    <ul class="options pull-right">
      <li class="welcome-link current">Welcome</li>

      <li class="design-link">Design</li>

      <li class="examples-link">Examples</li>

      <% if logged_in? %>
        <li class="open-dash">
          <a href="/admin">Open Dashboard</a>
        </li>
      <% else %>
        <li class="open-login">
          <%= link_to 'Login', new_session_url %>
        </li>
        <li class="open-signup">
          <%= link_to 'Sign Up', new_user_url %>
        </li>
      <% end %>
    </ul>
  </nav>

  <div class="row">
    <div class="col-sm-12">
      <h1 class="landing-title">BEAUTIFUL CLIENT PHOTO GALLERIES</h1>
      <h2 class="tag-line">The better way for modern photographers to share, deliver, proof and sell online.</h2>
      <div class="get-started-guest"><%= link_to 'Guest Login', new_session_url(demo: "true"), { method: "get", class: "guest-login-button", id: "guest-login-button"} %></div>
      <div class="check-out-demo">Register for a free account or try out a guest account.</div>
    </div>
    <div class="down-arrow moved">
      <div class="left-side"></div><div class="right-side"></div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function () {
    setInterval(function () {
      $('.down-arrow').toggleClass('moved');
    }, 400);

    $(".down-arrow").click(function() {
      $('html, body').animate({
        scrollTop: $('.design-examples').offset().top - 25
      }, 2000);
    });
  })
</script>

app/views/static_pages/_splash_navbar.html.erb
<div class="splash-navbar">
  <nav>
    <a href="/"><img src="http://images.karenling.net/aa/logo.png" height="16px" class="pull-left"></a>
    <ul class="options pull-right">
      <li class="welcome-link current">welcome</li>
      <li class="design-link">Design</li>
      <li class="examples-link">Examples</li>
      <li class="login">
        <a href="/session/new">Login</a>
      </li>
      <li>
        <%= button_to "Get Started", new_user_url, {method: 'get', class: 'get-started'} %>
      </li>
    </ul>
  </nav>
</div>

app/views/static_pages/admin.html.erb
<div id="content"></div>

app/views/static_pages/index.html.erb
<%= render 'shared/notice_and_errors' %>

<div id="content-landing">
  <%= render 'splash_navbar' %>
  <%= render 'main' %>
  <%= render 'design_examples' %>
  <%= render 'example_albums' %>
  <%= render 'bottom_info' %>
</div>

app/views/static_pages/public.html.erb
<div id="content-public"></div>