config/routes.rb
Rails.application.routes.draw do
  root  'static_pages#index'

  get  '/users' => 'static_pages#public'
  get '/admin' => 'static_pages#admin'

  resources :users, only: [:new, :create] do
    collection do
      get 'activate'
      get 'recovery'
      post 'reset_password'
      post 'create_new_password'
    end
  end

  resources :album_sessions, only: [:new, :create, :destroy, :index]
  resource :session, only: [:new, :create, :destroy]

  namespace :api, defaults: { format: :json } do
    get 'users/:user_id', to: 'public_users#show', as: "public_user"
    get 'users/:user_id/albums', to: 'public_albums#index', as: 'public_albums'
    get 'users/:user_id/albums/:id', to: 'public_albums#show', as: "public_album"
    resources :owners, only: [:show, :update]
    resources :albums, except: [:new, :edit]
    resources :subalbums, only: [:create, :update, :destroy, :show]
    resources :photos, only: [:create, :update, :destroy]
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  business_name   :string           not null
#  website         :string           not null
#  username        :string
#  created_at      :datetime
#  updated_at      :datetime
#  screenshot      :string
#  avatar          :string
#

class User < ActiveRecord::Base
  has_many(
    :albums,
    class_name: 'Album',
    foreign_key: :user_id,
    dependent: :destroy
  )

  attr_reader :password
  validates :business_name, :website, :email, :password_digest, :session_token,  presence: true
  validates :email, :password_digest, :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token, :ensure_activation_token

  def ensure_activation_token
    self.activation_token ||= SecureRandom::urlsafe_base64
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
    self.session_token
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    user && user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :if_logged_in, only: [:new]

  def new
    @user = User.new
    render :new
  end

  def index
    @users = User.all
    render json: @users
  end

  def show
    @user = User.find(params[:id])
    render json: @user
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = ['Created account! Please check your email to activate your account']
      UserMailer.welcome_email(@user).deliver_now
      redirect_to new_session_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if params[:user][:old_password] && !@user.is_password?(params[:user][:old_password])
      render json: 'Old password is incorrect.', status: :unprocessable_entity
      return
    end

    if @user.update(user_params)
      flash.now[:notice] = ['Successfully updated user!']
      render json: @user
    else
      flash.now[:errors] = @user.errors.full_messages
      render json: @user.errors.full_messages, status: :unprocessable_entity
    end
  end

  def activate
    @user = User.find_by(activation_token: params[:activation_token])
    
    if @user
      @user.activated = true
      @user.activation_token = SecureRandom::urlsafe_base64
      @user.save
      flash[:notice] = ["You have successfully activated your account!"]
      log_in_user!(@user)
      redirect_to admin_url
    else
      flash[:errors] = ["Account does not exist."]
      redirect_to new_user_url
    end
  end

  def recovery

    @user = User.find_by(activation_token: params[:activkey])
    if params[:activkey] && !@user # if we have an activkey but the user doesn't exist
      @no_user = "Incorrect recovery link."
      render :recovery
    end
  end


  def reset_password
    @user = User.find_by(email: params[:user][:email])
    if !@user
      flash.now[:errors] = ['Email is incorrect']
      render :recovery
      return
    end

    UserMailer.reset_password(@user).deliver_now
    @check_mail = "Please check your email. An instruction was sent to your email address."
    render :recovery
  end

  def create_new_password
    @user = User.find_by(activation_token: params[:activkey] )
    if @user && params[:user][:password] == params[:user][:retype_password]
      @user.password = params[:user][:password]
      @user.activation_token = SecureRandom::urlsafe_base64
      if @user.save
        flash[:notice] = ["You have successfully updated your password."]
        redirect_to new_session_url
        return
      else
        flash[:errors] = @user.errors.full_messages
        redirect_to action: :recovery, activkey: params[:activkey]
        return
      end
    elsif @user && params[:user][:password] != params[:user][:retype_password]
      flash[:errors] = ['Passwords do not match.']
      redirect_to action: :recovery, activkey: params[:activkey]
      return
    elsif !@user
      flash.now[:errors] = ['Account does not exist.']
      render :recovery
      return
    end
  end

  private
    def user_params
      params.require(:user).permit(:business_name, :website, :email, :password, :username)
    end

    def if_logged_in
      if logged_in?
        redirect_to "/admin"
      end
    end
end

app/views/users/new.html.erb
<div class="container sign-up-page">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <a href="/"><img class="logo" src="http://images.karenling.net/aa/logo.png" width="274px"></a>

      <div class="sign-up-free">
        <b>Sign up for free.</b> No credit card required.
      </div>

      <%= render 'shared/notice_and_errors' %>

      <form action="<%= users_url %>" method="post" class="form-group">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

        <input class="form-control" type="text" id="user-buinsess_name" name="user[business_name]" value="<% @user.business_name %>" placeholder="Business Name">

        <input class="form-control" type="text" id="user-website" name="user[website]" value="<% @user.website %>" placeholder="Website">

        <input class="form-control" type="text" id="user-email" name="user[email]" value="<%= @user.email %>" placeholder="you@email.com">

        <input class="form-control" type="password" id="user-password" name="user[password]" placeholder="Password">

        <input class="btn btn-primary submit-user" type="submit" value="Get Started">
      </form>

      <%= link_to 'Guest Login', new_session_url(demo: "true"), { method: "get", class: "guest-login-button"} %>
    </div>
  </div>
</div>

app/views/users/recovery.html.erb
<div class="container recovery-page">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2 col-md-4 col-md-offset-4">
      <a href="/"><img class="logo" src="http://images.karenling.net/aa/logo.png" width="274px"></a>

      <% if @no_user %>
        <p class="desc">
          <%= @no_user %>
        </p>
        <%= button_to "Back to login", new_session_url, { method: 'get', class: "reset-password" } %>
      <% elsif @check_mail %>
        <p class="desc">
          <%= @check_mail %>
        </p>
        <%= button_to "Back to login", new_session_url, { method: 'get', class: "reset-password" } %>
      <% elsif params[:activkey] %>
        <p class="desc">
          <b>Password reset.</b> Enter your new password.
        </p>

        <%= render 'shared/notice_and_errors' %>

        <form class="form-group" action="<%= create_new_password_users_url(activkey: params[:activkey]) %>" method="post">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
          <input type="password" name="user[password]" id="user-password" class="form-control" placeholder="New password">
          <input type="password" name="user[retype_password]" id="user-retype_password" class="form-control" placeholder="Retype new password">
          <input type="submit" class="reset-password" value="Save">
        </form>
      <% elsif !params[:activkey] %>

        <p class="desc">
          <b>Password reset.</b> Please enter the email address you used to create your account. An email will be sent to you with further instructions on resetting your password.
        </p>

        <%= render 'shared/notice_and_errors' %>

        <form class="form-group" action="<%= reset_password_users_url %>" method="post">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
          <input type="text" name="user[email]" class="form-control" placeholder="you@email.com">
          <input type="submit" class="recover-password" value="Send Email">
        </form>
      <% end %>

    </div>
  </div>
</div>